/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { access, readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import * as log from './utilities/log.ts';
import { getBanner } from './utilities/get-banner.ts';

const elementsDir = fileURLToPath(new URL('../scss/elements', import.meta.url));
const docsDir = fileURLToPath(new URL('../docs/content/elements', import.meta.url));

type ScssParameter = {
  name: string;
  type: string;
  default: string;
}

function parseScssDoc(source: string): ScssParameter[] | null {
  const match = source.match(/((?:\/\/\/[^\n]*\n)+)@mixin styles/);

  if (!match) {
    return null;
  }

  const lines = match[1]
    .split('\n')
    .map((l) => l.replace(/^\/\/\/\s?/, '').trim())
    .filter(Boolean);

  const parameters: ScssParameter[] = [];

  for (const line of lines) {
    // @param {type} name [default]
    // @param {type} name.key [default]
    const paramMatch = line.match(/^@param\s+\{([^}]+)\}\s+([\w.-]+)\s+\[((?:[^\[\]]|\[[^\]]*\])*)\]/);

    if (paramMatch) {
      const name = paramMatch[2].trim().replace(/config.?/, '');

      if (name) {
        parameters.push({
          name,
          type: paramMatch[1].trim().replaceAll(/ \| /g, '\n| '),
          default: paramMatch[3].trim(),
        });
      }
    }
  }

  return parameters;
}

const summary = {
  skipped: 0,
  succeeded: 0,
};

const elementFolders = await readdir(elementsDir);

for (const folder of elementFolders) {
  const scssPath = join(elementsDir, folder, 'index.scss');
  const docsPath = join(docsDir, folder);

  try {
    await access(docsPath);
  } catch {
    log.info(`Skipping ${folder} (no matching docs folder)…`);
    summary.skipped++;
    continue;
  }

  const source = await readFile(scssPath, 'utf8');
  const docs = parseScssDoc(source);

  if (!docs) {
    log.warning(`Skipping ${folder} (could not parse scss docs)…`);
    summary.skipped++;
    continue;
  }

  const output = `${getBanner('js')}
// This file is generated by running "npm run build:scss-docs".
// Do not manually edit this file as changes will be lost.

import { ScssDoc } from '@/model/ScssDoc';

const docs = new ScssDoc();

${docs.map((parameter) => `docs.parameters.set('${parameter.name}', {
  type: \`${parameter.type}\`,
  default: \`${parameter.default}\`,
});`).join('\n\n')}

export default docs;
`;

  const outFile = join(docsPath, 'scss.ts');

  try {
    await writeFile(outFile, output, 'utf8');

    log.success(`Wrote ${folder}/scss.ts`);
    summary.succeeded++;
  } catch (error) {
    log.error(`Error writing ${folder}/scss.ts`, '\n', error);
    process.exit(1);
  }
}

log.summary(`Wrote ${summary.succeeded} scss docs (${summary.skipped} skipped)`);
