/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { readFile, writeFile } from 'node:fs/promises';

import * as log from './utilities/log.ts';
import { getBanner } from './utilities/get-banner.ts';

const iconIds = [
  'arrow--right',
  'calendar',
  'caret--down',
  'checkbox--checked--filled',
  'checkbox--indeterminate--filled',
  'checkbox',
  'checkmark',
  'chevron--down',
  'close',
  'event--schedule',
  'search',
  'time',
  'warning--filled',
];

let scss = `${getBanner('css')}
// This file is generated by running "npm run build:icons".
// Do not manually edit this file as changes will be lost.

/// @group icons
/// @param {Length} size [1rem]
@mixin -icon($size: 1rem) {
  @if ($size != null) {
    block-size: $size;
    inline-size: $size;
  }

  background-color: currentColor;
}
`;

async function buildIcon(id: string) {
  const path = await import.meta.resolve?.(`@carbon/icons/svg/32/${id}.svg`);

  if (path) {
    try {
      const svg = await readFile(new URL(path));

      const dataUrl = 'data:image/svg+xml,' + svg
        .toString()
        .replaceAll('"', '\'');

      scss += `
/// @group icons
/// @param {Length} size [1rem]
@mixin ${id}($args...) {
  @include -icon($args...);
  mask-image: url("${dataUrl}");
}
`;

      log.info(`Loaded ${id}`);
    } catch (error) {
      log.error(`Error loading ${id}`, '\n', error);
      process.exit(1);
    }
  }
}

async function writeScss() {
  const path = await import.meta.resolve?.(`../src/utilities/_icons.scss`);

  if (path) {
    try {
      await writeFile(new URL(path), scss);

      log.success(`Wrote _icons.scss`);
    }  catch (error) {
      log.error(`Error writing _icons.scss`, '\n', error);
      process.exit(1);
    }
  }
}

for (const id of iconIds) {
  await buildIcon(id);
}

writeScss();
