/**
 * Copyright IBM Corp. 2026
 * 
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

// This file is generated by running "npm run build:scss-docs".
// Do not manually edit this file as changes will be lost.

import { ScssDoc } from '@/model/ScssDoc';

const docs = new ScssDoc();

docs.parameters.set('selector', {
  type: `Selector`,
  default: `'hr'`,
});

docs.parameters.set('kind', {
  type: `'subtle'
| 'strong'`,
  default: `'subtle'`,
});

export default docs;
