name: Publish CDN artifacts to Cloud Object Storage

on:
  workflow_dispatch:
  push:
    tags:
      # Matches tags that have the shape `vX.Y.Z` or `vX.Y.Z-rc.X` Reference:
      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#onpushpull_requesttagsbranches
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-cdn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: |
          npm ci
      - name: Build project
        run: |
          npm run build

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Configure IBM Cloud credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.COMMON_COS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.COMMON_COS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.COMMON_COS_REGION }}

      - name: Upload CDN artifacts
        run: |
          upload() {
            local DEST=$1
            echo "Uploading to $DEST"
            aws s3 sync css \
              s3://${{ secrets.COMMON_COS_BUCKET }}/$DEST \
              --acl public-read \
              --follow-symlinks \
              --endpoint-url https://${{ secrets.COMMON_COS_ENDPOINT }}
          }

        
          # Upload the CDN artifacts to the `latest` tag folder
          # ie. https://1.www.s81c.com/common/carbon/element-styles/tag/v0/latest/editorial.css
          TAG=$(echo "${{ steps.package-version.outputs.current-version }}" | grep -q '-' && echo "next" || echo "latest")
          upload "common/carbon/element-styles/tag/v0/$TAG"          

          # Upload the CDN artifacts to versioned folder
          # ie. https://1.www.s81c.com/common/carbon/element-styles/version/v0.2.0/editorial.css
          upload "common/carbon/element-styles/version/v${{ steps.package-version.outputs.current-version }}"
